### PR TITLE
A few updates

### PR DESCRIPTION
**Pull request by isuftin**

### CODE REVIEW

**Comment by zmoore-usgs** [comment]
👍 All of this makes sense to me

**Comment by isuftin** [comment]
There may be a few more incoming...

**Comment by isuftin** [comment]
After the latest push and the following commandset (local docker-machine), I have:

```
$ export DOCKER_ENGINE_IP=`docker-machine ip workbench`
$ ./launch_backing_services.sh
$ docker-compose up -d mlr-legacy-db

<wait wait wait>

$ docker-compose up mlr-legacy mlr-notification mlr-ddot-ingester mlr-wsc-file-exporter mlr-validator mlr-legacy-transformer mlr-gateway
$ docker ps -a
CONTAINER ID        IMAGE                                                                COMMAND                  CREATED              STATUS                        PORTS               NAMES
3b89dd503a15        cidasdpdasartip.cr.usgs.gov:8447/mlr/mlr-validator:latest            "./entrypoint.sh"        About a minute ago   Up About a minute (healthy)                       mlr-validator
9119144c2491        cidasdpdasartip.cr.usgs.gov:8447/mlr/mlr-ddot-ingester:latest        "./entrypoint.sh"        About a minute ago   Up About a minute (healthy)                       mlr-ddot-ingester
918a0bb02816        cidasdpdasartip.cr.usgs.gov:8447/mlr/mlr-wsc-file-exporter:latest    "./entrypoint.sh"        About a minute ago   Up About a minute (healthy)                       mlr-wsc-file-exporter
415b1515b28f        cidasdpdasartip.cr.usgs.gov:8447/mlr/mlr-gateway:latest              "./entrypoint.sh"        About a minute ago   Up About a minute (healthy)                       mlr-gateway
e0b50e81e61d        cidasdpdasartip.cr.usgs.gov:8447/mlr/mlr-notification:latest         "./entrypoint.sh"        About a minute ago   Up About a minute (healthy)                       mlr-notification
369a8dbb7d44        cidasdpdasartip.cr.usgs.gov:8447/mlr/mlr-legacy:latest               "./entrypoint.sh"        About a minute ago   Up About a minute (healthy)                       mlr-legacy
ea8c51043380        cidasdpdasartip.cr.usgs.gov:8447/mlr/mlr-legacy-transformer:latest   "./entrypoint.sh"        About a minute ago   Up About a minute (healthy)                       mlr-legacy-transformer
6bac042b0257        cidasdpdasartip.cr.usgs.gov:8447/mlr/mlr-legacy-db:latest            "docker-entrypoint.s…"   About a minute ago   Up About a minute (healthy)                       mlr-legacy-db
43524a7da874        cidasdpdasartip.cr.usgs.gov:8447/water_auth_server:latest            "./entrypoint.sh"        3 minutes ago        Up 3 minutes (healthy)                            water-auth
9f66189692d2        andrewgaul/s3proxy:latest                                            "/opt/s3proxy/run-do…"   3 minutes ago        Up 3 minutes                                      mock-s3
d7a5c25c21f1        digiplant/fake-smtp:latest                                           "/bin/sh -c 'java -j…"   3 minutes ago        Up 3 minutes                                      smtp-server
```

**Comment by isuftin** [comment]
This should be good to merge

**Pull request merged**
